### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shu-matsu09** [shu-matsu09/furima-33356#11]
# URL
https://furima-33356.herokuapp.com/

# Basic認証のIDとパスワード
ID: shu-matsu09
パスワード: eschatology

# 出品者用のメールアドレスとパスワード 
メールアドレス: test@sample
パスワード: 123abc

# 購入者用のメールアドレスとパスワード
メールアドレス: test2@sample
パスワード: 234bcd

# 購入用カードの番号・期限・セキュリティコード
カード番号: 4242424242424242
期限: 3 / 33
セキュリティコード: 123

**Comment by takumi0530** [comment]
@shu-matsu09 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/114979196-62e73e80-9ec5-11eb-81be-97c545cb7321.png)
